In [1]:
import pandas as pd
import os
import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt
import yfinance as yf
import numpy as np
import numpy as np
import pandas as pd
from joblib import Parallel, delayed
from fastdtw import fastdtw
from tqdm import tqdm
import tslearn
import tslearn.metrics
from sklearn.preprocessing import MinMaxScaler
import warnings

warnings.filterwarnings("ignore", category=RuntimeWarning)
warnings.simplefilter(action='ignore', category=FutureWarning)
from perform_utils import *

In [2]:
def get_simstock_result_abl(data_name):
    us = data_name #nasdaq_nasdaq_2022
    us = us[["Date","Stock_","Label"]]
    df_grouped = us.groupby('Stock_')['Label'].apply(list).reset_index()
    df_expanded = pd.DataFrame(df_grouped['Label'].tolist(), index=df_grouped['Stock_']).transpose()
    df_expanded = df_expanded.iloc[:us[us["Stock_"] == us["Stock_"].unique()[0]].shape[0], :]
    df_expanded.index = us[us["Stock_"] == us["Stock_"].unique()[0]].set_index("Date").index
    df_expanded = df_expanded.dropna(axis = 1)
    return df_expanded

### Diagonal Result

In [3]:
nasdaq_01 = get_simstock_result_abl(pd.read_csv("../abl_result/nasdaq_0.1.csv"))
nasdaq_03 = get_simstock_result_abl(pd.read_csv("../abl_result/nasdaq_0.3.csv"))
nasdaq_05 = get_simstock_result_abl(pd.read_csv("../abl_result/nasdaq_0.5.csv"))
nasdaq_07 = get_simstock_result("nasdaq_nasdaq_2022")
nasdaq_09 = get_simstock_result_abl(pd.read_csv("../abl_result/nasdaq_0.9.csv"))

sse_01 = get_simstock_result_abl(pd.read_csv("../abl_result/sse_0.1.csv"))
sse_03 = get_simstock_result_abl(pd.read_csv("../abl_result/sse_0.3.csv"))
sse_05 = get_simstock_result_abl(pd.read_csv("../abl_result/sse_0.5.csv"))
sse_07 = get_simstock_result("sse_sse_2022")
sse_09 = get_simstock_result_abl(pd.read_csv("../abl_result/sse_0.9.csv"))

tse_01 = get_simstock_result_abl(pd.read_csv("../abl_result/tse_0.1.csv"))
tse_03 = get_simstock_result_abl(pd.read_csv("../abl_result/tse_0.3.csv"))
tse_05 = get_simstock_result_abl(pd.read_csv("../abl_result/tse_0.5.csv"))
tse_07 = get_simstock_result("tse_tse_2022")
tse_09 = get_simstock_result_abl(pd.read_csv("../abl_result/tse_0.9.csv"))

szse_01 = get_simstock_result_abl(pd.read_csv("../abl_result/szse_0.1.csv"))
szse_03 = get_simstock_result_abl(pd.read_csv("../abl_result/szse_0.3.csv"))
szse_05 = get_simstock_result_abl(pd.read_csv("../abl_result/szse_0.5.csv"))
szse_07 = get_simstock_result("szse_szse_2022")
szse_09 = get_simstock_result_abl(pd.read_csv("../abl_result/szse_0.9.csv"))

In [4]:
nasdaq_01_DTW, nasdaq_01_corr = calculate_distance_matrix(nasdaq_01.values, nasdaq_01, True)
nasdaq_03_DTW, nasdaq_03_corr = calculate_distance_matrix(nasdaq_03.values, nasdaq_03, True)
nasdaq_05_DTW, nasdaq_05_corr = calculate_distance_matrix(nasdaq_05.values, nasdaq_05, True)
nasdaq_07_DTW, nasdaq_07_corr = calculate_distance_matrix(nasdaq_07.values, nasdaq_07, True)
nasdaq_09_DTW, nasdaq_09_corr = calculate_distance_matrix(nasdaq_09.values, nasdaq_09, True)

Calculating fastDTW distances: 100% 7815081/7815081 [03:02<00:00, 42854.49it/s]
Filling fastDTW distance matrix: 100% 7815081/7815081 [00:04<00:00, 1765845.43it/s]
Calculating fastDTW distances: 100% 7815081/7815081 [02:55<00:00, 44491.50it/s]
Filling fastDTW distance matrix: 100% 7815081/7815081 [00:04<00:00, 1835849.64it/s]
Calculating fastDTW distances: 100% 7815081/7815081 [02:57<00:00, 43953.34it/s]
Filling fastDTW distance matrix: 100% 7815081/7815081 [00:04<00:00, 1748769.98it/s]
Calculating fastDTW distances: 100% 7815081/7815081 [03:03<00:00, 42504.44it/s]
Filling fastDTW distance matrix: 100% 7815081/7815081 [00:04<00:00, 1711864.21it/s]
Calculating fastDTW distances: 100% 7815081/7815081 [02:57<00:00, 44058.69it/s]
Filling fastDTW distance matrix: 100% 7815081/7815081 [00:04<00:00, 1718632.19it/s]

In [5]:
sse_01_DTW, sse_01_corr = calculate_distance_matrix(sse_01.values, sse_01, True)
sse_03_DTW, sse_03_corr = calculate_distance_matrix(sse_03.values, sse_03, True)
sse_05_DTW, sse_05_corr = calculate_distance_matrix(sse_05.values, sse_05, True)
sse_07_DTW, sse_07_corr = calculate_distance_matrix(sse_07.values, sse_07, True)
sse_09_DTW, sse_09_corr = calculate_distance_matrix(sse_09.values, sse_09, True)

Calculating fastDTW distances: 100% 547581/547581 [00:11<00:00, 48977.74it/s]
Filling fastDTW distance matrix: 100% 547581/547581 [00:00<00:00, 1763574.86it/s]
Calculating fastDTW distances: 100% 547581/547581 [00:10<00:00, 50928.83it/s]
Filling fastDTW distance matrix: 100% 547581/547581 [00:00<00:00, 1768349.08it/s]
Calculating fastDTW distances: 100% 547581/547581 [00:10<00:00, 51010.35it/s]
Filling fastDTW distance matrix: 100% 547581/547581 [00:00<00:00, 1857102.34it/s]
Calculating fastDTW distances: 100% 547581/547581 [00:10<00:00, 50669.13it/s]
Filling fastDTW distance matrix: 100% 547581/547581 [00:00<00:00, 1742525.03it/s]
Calculating fastDTW distances: 100% 547581/547581 [00:11<00:00, 48262.51it/s]
Filling fastDTW distance matrix: 100% 547581/547581 [00:00<00:00, 1790720.79it/s]

In [6]:
szse_01_DTW, szse_01_corr = calculate_distance_matrix(szse_01.values, szse_01, True)
szse_03_DTW, szse_03_corr = calculate_distance_matrix(szse_03.values, szse_03, True)
szse_05_DTW, szse_05_corr = calculate_distance_matrix(szse_05.values, szse_05, True)
szse_07_DTW, szse_07_corr = calculate_distance_matrix(szse_07.values, szse_07, True)
szse_09_DTW, szse_09_corr = calculate_distance_matrix(szse_09.values, szse_09, True)

Calculating fastDTW distances: 100% 907878/907878 [00:18<00:00, 50037.99it/s]
Filling fastDTW distance matrix: 100% 907878/907878 [00:00<00:00, 1777094.08it/s]
Calculating fastDTW distances: 100% 907878/907878 [00:18<00:00, 49753.65it/s]
Filling fastDTW distance matrix: 100% 907878/907878 [00:00<00:00, 1877522.64it/s]
Calculating fastDTW distances: 100% 907878/907878 [00:19<00:00, 47363.53it/s]
Filling fastDTW distance matrix: 100% 907878/907878 [00:00<00:00, 1855468.28it/s]
Calculating fastDTW distances: 100% 907878/907878 [00:18<00:00, 49650.58it/s]
Filling fastDTW distance matrix: 100% 907878/907878 [00:00<00:00, 1857622.56it/s]
Calculating fastDTW distances: 100% 907878/907878 [00:19<00:00, 47208.91it/s]
Filling fastDTW distance matrix: 100% 907878/907878 [00:00<00:00, 1776560.98it/s]

In [7]:
tse_01_DTW, tse_01_corr = calculate_distance_matrix(tse_01.values, tse_01, True)
tse_03_DTW, tse_03_corr = calculate_distance_matrix(tse_03.values, tse_03, True)
tse_05_DTW, tse_05_corr = calculate_distance_matrix(tse_05.values, tse_05, True)
tse_07_DTW, tse_07_corr = calculate_distance_matrix(tse_07.values, tse_07, True)
tse_09_DTW, tse_09_corr = calculate_distance_matrix(tse_09.values, tse_09, True)

Calculating fastDTW distances: 100% 3991725/3991725 [01:25<00:00, 46654.36it/s]
Filling fastDTW distance matrix: 100% 3991725/3991725 [00:02<00:00, 1777848.73it/s]
Calculating fastDTW distances: 100% 3991725/3991725 [01:26<00:00, 46290.18it/s]
Filling fastDTW distance matrix: 100% 3991725/3991725 [00:02<00:00, 1859620.38it/s]
Calculating fastDTW distances: 100% 3991725/3991725 [01:26<00:00, 45977.90it/s]
Filling fastDTW distance matrix: 100% 3991725/3991725 [00:01<00:00, 2086982.49it/s]
Calculating fastDTW distances: 100% 3991725/3991725 [01:25<00:00, 46731.91it/s]
Filling fastDTW distance matrix: 100% 3991725/3991725 [00:02<00:00, 1817030.73it/s]
Calculating fastDTW distances: 100% 3991725/3991725 [01:25<00:00, 46462.19it/s]
Filling fastDTW distance matrix: 100% 3991725/3991725 [00:02<00:00, 1857302.05it/s]

In [8]:
nasdaq_01_DTW

Stock_,A,AA,AACG,AADI,AAL,AAOI,AAON,AAP,AAPL,AAT,...,ZTEK,ZTO,ZTR,ZTS,ZUMZ,ZUO,ZVRA,ZWS,ZYME,ZYXI
Stock_,,,,,,,,,,,,,,,,,,,,,
A,0.000000,72.048536,63.437925,134.757297,124.374742,47.149060,49.831609,148.922401,54.933429,80.806253,...,82.380971,77.558545,44.443143,47.093334,55.475760,68.106491,73.996553,53.309807,81.825760,43.424531
AA,72.048536,0.000000,47.115708,54.058755,39.631279,49.961499,67.717150,58.307808,58.603332,33.992568,...,37.959024,35.607262,45.641286,72.538048,45.779460,36.827659,39.979992,44.380486,36.940576,78.649983
AACG,63.437925,47.115708,0.000000,66.691760,53.626673,46.199209,61.090175,79.392162,56.848693,45.203730,...,49.355990,45.432990,41.993413,44.821408,53.661312,37.776250,38.764588,46.551825,39.934007,65.872958
AADI,134.757297,54.058755,66.691760,0.000000,30.679749,91.264340,123.685511,10.241661,102.109665,36.897661,...,56.178368,50.093595,110.272711,139.272357,79.943893,56.590206,64.617339,92.147112,71.292322,139.313830
AAL,124.374742,39.631279,53.626673,30.679749,0.000000,66.939233,107.139383,25.736203,92.483638,34.291595,...,46.479160,32.608875,65.489115,105.991947,56.089901,38.151286,40.484272,69.096544,42.962073,115.614160
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZUO,68.106491,36.827659,37.776250,56.590206,38.151286,41.801780,68.467824,65.928506,51.883349,38.861353,...,38.890728,37.138552,36.418321,57.337136,41.642114,0.000000,36.242814,33.860901,35.374893,74.281406
ZVRA,73.996553,39.979992,38.764588,64.617339,40.484272,47.706673,70.128624,72.314196,56.489760,38.761371,...,44.526362,35.533054,46.445064,52.387004,45.020581,36.242814,0.000000,54.354745,30.591677,82.826782
ZWS,53.309807,44.380486,46.551825,92.147112,69.096544,49.219354,57.834349,94.899228,44.988387,60.335140,...,50.804102,45.576399,40.296625,50.706671,41.601567,33.860901,54.354745,0.000000,46.259577,54.661583
ZYME,81.825760,36.940576,39.934007,71.292322,42.962073,54.331569,66.179993,70.679990,72.719201,32.678719,...,33.291583,32.475984,48.019466,62.327744,38.159773,35.374893,30.591677,46.259577,0.000000,71.675101
ZYXI,43.424531,78.649983,65.872958,139.313830,115.614160,54.779312,50.728386,131.097349,49.267280,85.181593,...,69.774809,80.510543,49.942515,56.784369,60.666814,74.281406,82.826782,54.661583,71.675101,0.000000

In [9]:
corr1_us = pd.read_csv("./origin_result/corr1_us.csv")
corr1_sse = pd.read_csv("./origin_result/corr1_sse.csv")
corr1_tse = pd.read_csv("./origin_result/corr1_tse.csv")
corr1_szse = pd.read_csv("./origin_result/corr1_szse.csv")
real_df = pd.read_csv("./origin_result/real_df.csv")
real_sse_df = pd.read_csv("./origin_result/real_sse_df.csv")
real_tse_df = pd.read_csv("./origin_result/real_tse_df.csv")
real_szse_df = pd.read_csv("./origin_result/real_szse_df.csv")
DTW_scale_gt_us_us, corr_scale_gt_us_us = calculate_distance_matrix(real_df.values, real_df, True)
DTW_scale_gt_sse_sse, corr_scale_gt_sse_sse = calculate_distance_matrix(real_sse_df.values, real_sse_df, True)
DTW_scale_gt_tse_tse, corr_scale_gt_tse_tse = calculate_distance_matrix(real_tse_df.values, real_tse_df, True)
DTW_scale_gt_szse_szse, corr_scale_gt_szse_szse = calculate_distance_matrix(real_szse_df.values, real_szse_df, True)

Calculating fastDTW distances: 100% 7779540/7779540 [01:47<00:00, 72038.27it/s]
Filling fastDTW distance matrix: 100% 7779540/7779540 [00:04<00:00, 1691270.39it/s]
Calculating fastDTW distances: 100% 547581/547581 [00:06<00:00, 87456.74it/s]
Filling fastDTW distance matrix: 100% 547581/547581 [00:00<00:00, 1767242.85it/s]
Calculating fastDTW distances: 100% 3991725/3991725 [00:50<00:00, 79768.28it/s]
Filling fastDTW distance matrix: 100% 3991725/3991725 [00:02<00:00, 1763493.09it/s]
Calculating fastDTW distances: 100% 907878/907878 [00:10<00:00, 85745.15it/s]
Filling fastDTW distance matrix: 100% 907878/907878 [00:00<00:00, 1823396.84it/s]

In [10]:
def calculate_diagonal_perform_abl(corr1, data_01, data_03, data_05, data_07, data_09, gt_corr, gt_dtw, num_stocks):
    all_stock_list = list(corr1.columns)
    result_corr_list = []
    result_dtw_list = []
    corr1.index = corr1.columns
    
    for i in tqdm(all_stock_list, desc="Processing stocks"):
        corr1_list_ = list(corr1[i].nlargest(num_stocks).index)
        data_01_list = list(data_01[i].nlargest(num_stocks).index)
        data_03_list = list(data_03[i].nlargest(num_stocks).index)
        data_05_list = list(data_05[i].nlargest(num_stocks).index)
        data_07_list = list(data_07[i].nlargest(num_stocks).index)
        data_09_list = list(data_09[i].nlargest(num_stocks).index)
        
        result_corr = {
            'symbol': i,
            'data_01_mean': round(gt_corr.loc[gt_corr.columns.intersection(data_01_list)][i].values[1:].mean(), 3),
            'data_03_mean': round(gt_corr.loc[gt_corr.columns.intersection(data_03_list)][i].values[1:].mean(), 3),
            'data_05_mean': round(gt_corr.loc[gt_corr.columns.intersection(data_05_list)][i].values[1:].mean(), 3),
            'data_07_mean': round(gt_corr.loc[gt_corr.columns.intersection(data_07_list)][i].values[1:].mean(), 3),
            'data_09_mean': round(gt_corr.loc[gt_corr.columns.intersection(data_09_list)][i].values[1:].mean(), 3),


        }
        
        result_corr_list.append(result_corr)
        result_dtw = {
            'symbol': i,
            'data_01_mean': round(gt_dtw.loc[gt_dtw.columns.intersection(data_01_list)][i].values[1:].mean(), 3),
            'data_03_mean': round(gt_dtw.loc[gt_dtw.columns.intersection(data_03_list)][i].values[1:].mean(), 3),
            'data_05_mean': round(gt_dtw.loc[gt_dtw.columns.intersection(data_05_list)][i].values[1:].mean(), 3),
            'data_07_mean': round(gt_dtw.loc[gt_dtw.columns.intersection(data_07_list)][i].values[1:].mean(), 3),
            'data_09_mean': round(gt_dtw.loc[gt_dtw.columns.intersection(data_09_list)][i].values[1:].mean(), 3),


            }
        result_dtw_list.append(result_dtw)
    result_corr = pd.DataFrame(result_corr_list)
    result_dtw = pd.DataFrame(result_dtw_list)        
    result_corr["top_k"] = num_stocks-1
    result_dtw["top_k"] = num_stocks-1        
    return result_corr, result_dtw

In [11]:
corr_1_us_us, dtw_1_us_us = calculate_diagonal_perform_abl(corr1_us,
                                                           nasdaq_01_corr,
                                                           nasdaq_03_corr,
                                                           nasdaq_05_corr,
                                                           nasdaq_07_corr,
                                                           nasdaq_09_corr,
                                                           DTW_scale_gt_us_us,
                                                           corr_scale_gt_us_us, 2)

corr_3_us_us, dtw_3_us_us = calculate_diagonal_perform_abl(corr1_us,
                                                           nasdaq_01_corr,
                                                           nasdaq_03_corr,
                                                           nasdaq_05_corr,
                                                           nasdaq_07_corr,
                                                           nasdaq_09_corr,
                                                           DTW_scale_gt_us_us,
                                                           corr_scale_gt_us_us, 4)

corr_5_us_us, dtw_5_us_us = calculate_diagonal_perform_abl(corr1_us,
                                                           nasdaq_01_corr,
                                                           nasdaq_03_corr,
                                                           nasdaq_05_corr,
                                                           nasdaq_07_corr,
                                                           nasdaq_09_corr,
                                                           DTW_scale_gt_us_us,
                                                           corr_scale_gt_us_us, 6)

corr_7_us_us, dtw_7_us_us = calculate_diagonal_perform_abl(corr1_us,
                                                           nasdaq_01_corr,
                                                           nasdaq_03_corr,
                                                           nasdaq_05_corr,
                                                           nasdaq_07_corr,
                                                           nasdaq_09_corr,
                                                           DTW_scale_gt_us_us,
                                                           corr_scale_gt_us_us, 8)

corr_9_us_us, dtw_9_us_us = calculate_diagonal_perform_abl(corr1_us,
                                                           nasdaq_01_corr,
                                                           nasdaq_03_corr,
                                                           nasdaq_05_corr,
                                                           nasdaq_07_corr,
                                                           nasdaq_09_corr,
                                                           DTW_scale_gt_us_us,
                                                           corr_scale_gt_us_us, 10)

Processing stocks: 100% 3944/3944 [00:44<00:00, 87.88it/s]
Processing stocks: 100% 3944/3944 [00:40<00:00, 97.47it/s]
Processing stocks: 100% 3944/3944 [00:40<00:00, 97.28it/s]
Processing stocks: 100% 3944/3944 [00:41<00:00, 94.71it/s]
Processing stocks: 100% 3944/3944 [00:41<00:00, 94.92it/s]

In [12]:

get_corr_us = pd.concat([dtw_1_us_us.set_index("symbol").iloc[:, :-1].mean(), 
                       dtw_3_us_us.set_index("symbol").iloc[:, :-1].mean(),
                       dtw_5_us_us.set_index("symbol").iloc[:, :-1].mean(),
                       dtw_7_us_us.set_index("symbol").iloc[:, :-1].mean(),
                       dtw_9_us_us.set_index("symbol").iloc[:, :-1].mean()], axis = 1)


get_dtw_us = pd.concat([corr_1_us_us.set_index("symbol").iloc[:, :-1].mean(), 
                        corr_3_us_us.set_index("symbol").iloc[:, :-1].mean(),
                        corr_5_us_us.set_index("symbol").iloc[:, :-1].mean(),
                        corr_7_us_us.set_index("symbol").iloc[:, :-1].mean(),
                        corr_9_us_us.set_index("symbol").iloc[:, :-1].mean()], axis = 1)

In [13]:
get_corr_us.index = ["$\lambda$=0.1", "$\lambda$=0.3", "$\lambda$=0.5", "$\lambda$=0.7", "$\lambda$=0.9"]
get_corr_us.columns = ["Top@1", "Top@3", "Top@5","Top@7","Top@9"]

get_dtw_us.index = ["$\lambda$=0.1", "$\lambda$=0.3", "$\lambda$=0.5", "$\lambda$=0.7", "$\lambda$=0.9"]
get_dtw_us.columns = ["Top@1", "Top@3", "Top@5","Top@7","Top@9"]

In [14]:
get_corr_us_ = get_corr_us.copy()

In [15]:
get_dtw_us_ = get_dtw_us.copy()

In [16]:
corr_1_us_us, dtw_1_us_us = calculate_diagonal_perform_abl(corr1_sse,
                                                           sse_01_corr,
                                                           sse_03_corr,
                                                           sse_05_corr,
                                                           sse_07_corr,
                                                           sse_09_corr,
                                                           DTW_scale_gt_sse_sse,
                                                           corr_scale_gt_sse_sse, 2)

corr_3_us_us, dtw_3_us_us = calculate_diagonal_perform_abl(corr1_sse,
                                                           sse_01_corr,
                                                           sse_03_corr,
                                                           sse_05_corr,
                                                           sse_07_corr,
                                                           sse_09_corr,
                                                           DTW_scale_gt_sse_sse,
                                                           corr_scale_gt_sse_sse, 4)

corr_5_us_us, dtw_5_us_us = calculate_diagonal_perform_abl(corr1_sse,
                                                           sse_01_corr,
                                                           sse_03_corr,
                                                           sse_05_corr,
                                                           sse_07_corr,
                                                           sse_09_corr,
                                                           DTW_scale_gt_sse_sse,
                                                           corr_scale_gt_sse_sse, 6)

corr_7_us_us, dtw_7_us_us = calculate_diagonal_perform_abl(corr1_sse,
                                                           sse_01_corr,
                                                           sse_03_corr,
                                                           sse_05_corr,
                                                           sse_07_corr,
                                                           sse_09_corr,
                                                           DTW_scale_gt_sse_sse,
                                                           corr_scale_gt_sse_sse, 8)

corr_9_us_us, dtw_9_us_us = calculate_diagonal_perform_abl(corr1_sse,
                                                           sse_01_corr,
                                                           sse_03_corr,
                                                           sse_05_corr,
                                                           sse_07_corr,
                                                           sse_09_corr,
                                                           DTW_scale_gt_sse_sse,
                                                           corr_scale_gt_sse_sse, 10)

Processing stocks: 100% 1046/1046 [00:09<00:00, 114.65it/s]
Processing stocks: 100% 1046/1046 [00:08<00:00, 120.37it/s]
Processing stocks: 100% 1046/1046 [00:08<00:00, 119.17it/s]
Processing stocks: 100% 1046/1046 [00:08<00:00, 118.99it/s]
Processing stocks: 100% 1046/1046 [00:08<00:00, 118.08it/s]

In [17]:

get_corr_us = pd.concat([dtw_1_us_us.set_index("symbol").iloc[:, :-1].mean(), 
                       dtw_3_us_us.set_index("symbol").iloc[:, :-1].mean(),
                       dtw_5_us_us.set_index("symbol").iloc[:, :-1].mean(),
                       dtw_7_us_us.set_index("symbol").iloc[:, :-1].mean(),
                       dtw_9_us_us.set_index("symbol").iloc[:, :-1].mean()], axis = 1)


get_dtw_us = pd.concat([corr_1_us_us.set_index("symbol").iloc[:, :-1].mean(), 
                        corr_3_us_us.set_index("symbol").iloc[:, :-1].mean(),
                        corr_5_us_us.set_index("symbol").iloc[:, :-1].mean(),
                        corr_7_us_us.set_index("symbol").iloc[:, :-1].mean(),
                        corr_9_us_us.set_index("symbol").iloc[:, :-1].mean()], axis = 1)

In [18]:
get_corr_us.index = ["$\lambda$=0.1", "$\lambda$=0.3", "$\lambda$=0.5", "$\lambda$=0.7", "$\lambda$=0.9"]
get_corr_us.columns = ["Top@1", "Top@3", "Top@5","Top@7","Top@9"]

get_dtw_us.index = ["$\lambda$=0.1", "$\lambda$=0.3", "$\lambda$=0.5", "$\lambda$=0.7", "$\lambda$=0.9"]
get_dtw_us.columns = ["Top@1", "Top@3", "Top@5","Top@7","Top@9"]

In [19]:
get_corr_sse = get_corr_us.copy()

In [20]:
get_dtw_sse = get_dtw_us.copy()

In [21]:
corr_1_us_us, dtw_1_us_us = calculate_diagonal_perform_abl(corr1_tse,
                                                           tse_01_corr,
                                                           tse_03_corr,
                                                           tse_05_corr,
                                                           tse_07_corr,
                                                           tse_09_corr,
                                                           DTW_scale_gt_tse_tse,
                                                           corr_scale_gt_tse_tse, 2)

corr_3_us_us, dtw_3_us_us = calculate_diagonal_perform_abl(corr1_tse,
                                                           tse_01_corr,
                                                           tse_03_corr,
                                                           tse_05_corr,
                                                           tse_07_corr,
                                                           tse_09_corr,
                                                           DTW_scale_gt_tse_tse,
                                                           corr_scale_gt_tse_tse, 4)

corr_5_us_us, dtw_5_us_us = calculate_diagonal_perform_abl(corr1_tse,
                                                           tse_01_corr,
                                                           tse_03_corr,
                                                           tse_05_corr,
                                                           tse_07_corr,
                                                           tse_09_corr,
                                                           DTW_scale_gt_tse_tse,
                                                           corr_scale_gt_tse_tse, 6)

corr_7_us_us, dtw_7_us_us = calculate_diagonal_perform_abl(corr1_tse,
                                                           tse_01_corr,
                                                           tse_03_corr,
                                                           tse_05_corr,
                                                           tse_07_corr,
                                                           tse_09_corr,
                                                           DTW_scale_gt_tse_tse,
                                                           corr_scale_gt_tse_tse, 8)

corr_9_us_us, dtw_9_us_us = calculate_diagonal_perform_abl(corr1_tse,
                                                           tse_01_corr,
                                                           tse_03_corr,
                                                           tse_05_corr,
                                                           tse_07_corr,
                                                           tse_09_corr,
                                                           DTW_scale_gt_tse_tse,
                                                           corr_scale_gt_tse_tse, 10)

Processing stocks: 100% 2825/2825 [00:33<00:00, 85.04it/s]
Processing stocks: 100% 2825/2825 [00:29<00:00, 94.51it/s]
Processing stocks: 100% 2825/2825 [00:32<00:00, 86.26it/s]
Processing stocks: 100% 2825/2825 [00:33<00:00, 84.11it/s]
Processing stocks: 100% 2825/2825 [00:33<00:00, 85.06it/s]

In [22]:

get_corr_us = pd.concat([dtw_1_us_us.set_index("symbol").iloc[:, :-1].mean(), 
                       dtw_3_us_us.set_index("symbol").iloc[:, :-1].mean(),
                       dtw_5_us_us.set_index("symbol").iloc[:, :-1].mean(),
                       dtw_7_us_us.set_index("symbol").iloc[:, :-1].mean(),
                       dtw_9_us_us.set_index("symbol").iloc[:, :-1].mean()], axis = 1)


get_dtw_us = pd.concat([corr_1_us_us.set_index("symbol").iloc[:, :-1].mean(), 
                        corr_3_us_us.set_index("symbol").iloc[:, :-1].mean(),
                        corr_5_us_us.set_index("symbol").iloc[:, :-1].mean(),
                        corr_7_us_us.set_index("symbol").iloc[:, :-1].mean(),
                        corr_9_us_us.set_index("symbol").iloc[:, :-1].mean()], axis = 1)

In [23]:
get_corr_us.index = ["$\lambda$=0.1", "$\lambda$=0.3", "$\lambda$=0.5", "$\lambda$=0.7", "$\lambda$=0.9"]
get_corr_us.columns = ["Top@1", "Top@3", "Top@5","Top@7","Top@9"]

get_dtw_us.index = ["$\lambda$=0.1", "$\lambda$=0.3", "$\lambda$=0.5", "$\lambda$=0.7", "$\lambda$=0.9"]
get_dtw_us.columns = ["Top@1", "Top@3", "Top@5","Top@7","Top@9"]

In [24]:
get_corr_tse = get_corr_us.copy()

In [25]:
get_dtw_tse = get_dtw_us.copy()

In [26]:
corr_1_us_us, dtw_1_us_us = calculate_diagonal_perform_abl(corr1_szse,
                                                           szse_01_corr,
                                                           szse_03_corr,
                                                           szse_05_corr,
                                                           szse_07_corr,
                                                           szse_09_corr,
                                                           DTW_scale_gt_szse_szse,
                                                           corr_scale_gt_szse_szse, 2)

corr_3_us_us, dtw_3_us_us = calculate_diagonal_perform_abl(corr1_szse,
                                                           szse_01_corr,
                                                           szse_03_corr,
                                                           szse_05_corr,
                                                           szse_07_corr,
                                                           szse_09_corr,
                                                           DTW_scale_gt_szse_szse,
                                                           corr_scale_gt_szse_szse, 4)


corr_5_us_us, dtw_5_us_us = calculate_diagonal_perform_abl(corr1_szse,
                                                           szse_01_corr,
                                                           szse_03_corr,
                                                           szse_05_corr,
                                                           szse_07_corr,
                                                           szse_09_corr,
                                                           DTW_scale_gt_szse_szse,
                                                           corr_scale_gt_szse_szse, 6)


corr_7_us_us, dtw_7_us_us = calculate_diagonal_perform_abl(corr1_szse,
                                                           szse_01_corr,
                                                           szse_03_corr,
                                                           szse_05_corr,
                                                           szse_07_corr,
                                                           szse_09_corr,
                                                           DTW_scale_gt_szse_szse,
                                                           corr_scale_gt_szse_szse, 8)


corr_9_us_us, dtw_9_us_us = calculate_diagonal_perform_abl(corr1_szse,
                                                           szse_01_corr,
                                                           szse_03_corr,
                                                           szse_05_corr,
                                                           szse_07_corr,
                                                           szse_09_corr,
                                                           DTW_scale_gt_szse_szse,
                                                           corr_scale_gt_szse_szse, 10)

Processing stocks: 100% 1347/1347 [00:13<00:00, 96.26it/s]
Processing stocks: 100% 1347/1347 [00:11<00:00, 116.90it/s]
Processing stocks: 100% 1347/1347 [00:11<00:00, 115.96it/s]
Processing stocks: 100% 1347/1347 [00:11<00:00, 114.34it/s]
Processing stocks: 100% 1347/1347 [00:11<00:00, 113.92it/s]

In [27]:

get_corr_us = pd.concat([dtw_1_us_us.set_index("symbol").iloc[:, :-1].mean(), 
                       dtw_3_us_us.set_index("symbol").iloc[:, :-1].mean(),
                       dtw_5_us_us.set_index("symbol").iloc[:, :-1].mean(),
                       dtw_7_us_us.set_index("symbol").iloc[:, :-1].mean(),
                       dtw_9_us_us.set_index("symbol").iloc[:, :-1].mean()], axis = 1)


get_dtw_us = pd.concat([corr_1_us_us.set_index("symbol").iloc[:, :-1].mean(), 
                        corr_3_us_us.set_index("symbol").iloc[:, :-1].mean(),
                        corr_5_us_us.set_index("symbol").iloc[:, :-1].mean(),
                        corr_7_us_us.set_index("symbol").iloc[:, :-1].mean(),
                        corr_9_us_us.set_index("symbol").iloc[:, :-1].mean()], axis = 1)

In [28]:
get_corr_us.index = ["$\lambda$=0.1", "$\lambda$=0.3", "$\lambda$=0.5", "$\lambda$=0.7", "$\lambda$=0.9"]
get_corr_us.columns = ["Top@1", "Top@3", "Top@5","Top@7","Top@9"]

get_dtw_us.index = ["$\lambda$=0.1", "$\lambda$=0.3", "$\lambda$=0.5", "$\lambda$=0.7", "$\lambda$=0.9"]
get_dtw_us.columns = ["Top@1", "Top@3", "Top@5","Top@7","Top@9"]

In [29]:
get_corr_szse = get_corr_us.copy()

In [30]:
get_dtw_szse = get_dtw_us.copy()

In [74]:
get_corr_us_.columns =  ["TOP@1", "TOP@3", "TOP@5","TOP@7","TOP@9"]
get_corr_sse.columns =  ["TOP@1", "TOP@3", "TOP@5","TOP@7","TOP@9"]
get_corr_szse.columns =  ["TOP@1", "TOP@3", "TOP@5","TOP@7","TOP@9"]
get_corr_tse.columns =  ["TOP@1", "TOP@3", "TOP@5","TOP@7","TOP@9"]

get_dtw_us_.columns =  ["TOP@1", "TOP@3", "TOP@5","TOP@7","TOP@9"]
get_dtw_sse.columns =  ["TOP@1", "TOP@3", "TOP@5","TOP@7","TOP@9"]
get_dtw_szse.columns =  ["TOP@1", "TOP@3", "TOP@5","TOP@7","TOP@9"]
get_dtw_tse.columns =  ["TOP@1", "TOP@3", "TOP@5","TOP@7","TOP@9"]

In [122]:
get_dtw_us_.round(4)

                 TOP@1    TOP@3    TOP@5    TOP@7    TOP@9
$\lambda$=0.1  14.3211  22.0003  24.9902  26.6191  27.6328
$\lambda$=0.3  13.6924  21.9408  24.8712  26.6015  27.6861
$\lambda$=0.5  13.1073  20.4898  23.3020  24.8633  25.8934
$\lambda$=0.7  12.2124  19.4629  22.1019  23.5986  24.6195
$\lambda$=0.9  12.3086  19.5703  22.2254  23.6872  24.6773

In [123]:
get_dtw_sse.round(4)

                 TOP@1    TOP@3    TOP@5    TOP@7    TOP@9
$\lambda$=0.1  13.9537  21.7294  24.7087  26.5307  27.7407
$\lambda$=0.3  12.6262  20.9044  23.6370  25.2049  26.3574
$\lambda$=0.5  11.0089  19.5019  22.5511  24.0833  25.0604
$\lambda$=0.7  11.2685  19.0090  21.5380  23.1172  24.2082
$\lambda$=0.9  11.5052  18.7520  21.5877  23.1732  24.2119

In [124]:
get_dtw_szse.round(4)

                 TOP@1    TOP@3    TOP@5    TOP@7    TOP@9
$\lambda$=0.1  13.2464  19.7050  22.2434  23.6564  24.7304
$\lambda$=0.3  14.1484  21.0873  23.8357  25.2652  26.2770
$\lambda$=0.5  15.0496  21.9856  24.4632  26.0794  27.0110
$\lambda$=0.7  12.0045  18.4121  20.7238  22.1577  23.1457
$\lambda$=0.9  12.3990  18.4378  21.0680  22.4532  23.3963

In [125]:
get_dtw_tse.round(4)

                 TOP@1    TOP@3    TOP@5    TOP@7    TOP@9
$\lambda$=0.1  19.4737  27.5245  31.0088  32.5306  33.7523
$\lambda$=0.3  18.5924  26.8110  29.9655  31.7022  32.7707
$\lambda$=0.5  17.7066  26.0258  28.8961  30.4193  31.3618
$\lambda$=0.7  14.6179  21.4850  24.2952  25.8992  26.7530
$\lambda$=0.9  14.1545  21.0788  23.8008  25.3369  26.2443